#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/xlUtil_go
  
  blListGen \
    -d ../xlUtil_go \
    -1L  \
    -u $DVCZ_UDIR \
    -X .ssh \
    $@
  
else
  echo "DEV_BASE is not defined"
fi
