#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/xlUtil_go
  
  rm -rf merletree/tmp/* 
  
  pySloc -L go cmd/gMerkleize/gMerkleize.go  -X *.pb.go -v $@
else
  echo "DEV_BASE is not defined"
fi
