#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/xlUtil_go
  
  pushd cmd/gMerkleize
  go build && go install
  popd
  
else
  echo "DEV_BASE is not defined"
fi
