[meta]
version = "0.1.0"

[project]
name = "xlUtil_go"
package = "xlUtil_go"
main_lang = "go"
version = "0.9.20"
version_date = "2017-11-11"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
copyright = "2014-2016"
description = "utilities for the XLattice Go projects"
dev_status = "alpha"
license = "mit"
relpath = "go/src/github.com/jddixon/xlUtil_go"
state = "shared"
url = "https://jddixon.github.io/xlUtil_go"

[go]
cmds = [ "gMerkleize",]
